### ISSUE TITLE
1.0.4: Missing migration for sync_enabled field + check_default_hostinterface NotImplementedError

### ISSUE THREAD

**Issue by therealiGor** [OpensourceICTSolutions/nbxsync#103]
**nbxsync version:** 1.0.4
**NetBox version:** [deine Version]
**Python version:** 3.12

## Bug 1: Missing migration for sync_enabled

After upgrading from 1.0.3 to 1.0.4, all synchost jobs fail with:

    AttributeError: 'ZabbixServerAssignment' object has no attribute 'sync_enabled'

The field `sync_enabled` is defined in the model but no migration exists for it in 1.0.4.
The column already exists in the DB (added by a previous version?) but Django's migration 
state doesn't know about it.

**Fix:** A migration adding `sync_enabled` to `ZabbixServerAssignment` and `ZabbixServer` 
is missing from the 1.0.4 package.

## Bug 2: NotImplementedError for check_default_hostinterface

After fixing Bug 1, synchost jobs fail with:

    NotImplementedError: HostSync does not implement `check_default_hostinterface()`.

The method exists in `hostsync.py` (line 464) but `run_zabbix_operation` cannot find it 
via `getattr` on the instance. 

The method is called in `synchost.py` line 36:
    self.check_default_hostinterface(assignment)

**Workaround:** Comment out the `check_default_hostinterface` call in synchost.py.

**Workaround for Bug 1:** Manually create and --fake apply a migration.

Both bugs together make 1.0.4 completely broken for host syncing.

**Comment by bvbaekel** [comment]
Hi,

In the future, could you please create an issue per bug? That would make handling these easier!

**Bug 1:** can you check again? The migration is [there](https://github.com/OpensourceICTSolutions/nbxsync/blob/main/nbxsync/migrations/0011_zabbixhostinterface_max_repetitions_and_more.py#L25) so this must be something else...

**Bug 2:** check_default_hostinterface() exists in the code, syncing hosts works... How can I reproduce this issue?
